#!/usr/bin/env python3
"""
LFS Builder Profiles Configuration
Defines all build profiles with flexible desktop, init system, and audio options
"""

PROFILES_CONFIG = {
    'minimal': {
        'description': 'Minimal command-line only system',
        'size_gb': 1,
        'build_time_hours': 2,
        'packages': ['base', 'network', 'ssh'],
        'desktop': 'none',
        'init_system': 'sysvinit',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': False,
        'privacy_tools': False,
        'live_system': False,
        'system_updater': False,
        'desktop_options': ['none'],
        'init_options': ['sysvinit', 'systemd', 'openrc'],
        'audio_options': ['none']
    },
    'xfce': {
        'description': 'XFCE desktop environment - lightweight and efficient',
        'size_gb': 4,
        'build_time_hours': 4,
        'packages': ['base', 'network', 'ssh', 'xorg', 'xfce', 'apps'],
        'desktop': 'xfce',
        'init_system': 'systemd',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['xfce', 'lxqt'],
        'init_options': ['systemd', 'sysvinit', 'openrc', 'runit'],
        'audio_options': ['none', 'cli', 'studio']
    },
    'gnome': {
        'description': 'GNOME desktop environment - modern and feature-rich',
        'size_gb': 8,
        'build_time_hours': 8,
        'packages': ['base', 'network', 'ssh', 'xorg', 'gnome', 'apps'],
        'desktop': 'gnome',
        'init_system': 'systemd',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['gnome', 'kde', 'xfce'],
        'init_options': ['systemd', 'openrc'],
        'audio_options': ['none', 'studio']
    },
    'kde': {
        'description': 'KDE Plasma - full-featured desktop environment',
        'size_gb': 10,
        'build_time_hours': 12,
        'packages': ['base', 'network', 'ssh', 'xorg', 'kde', 'apps', 'multimedia'],
        'desktop': 'kde',
        'init_system': 'systemd',
        'audio': 'studio',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['kde', 'gnome', 'xfce'],
        'init_options': ['systemd', 'openrc'],
        'audio_options': ['none', 'studio']
    },
    'lxqt': {
        'description': 'LXQt - extremely lightweight Qt desktop',
        'size_gb': 2,
        'build_time_hours': 3,
        'packages': ['base', 'network', 'ssh', 'xorg', 'lxqt', 'apps'],
        'desktop': 'lxqt',
        'init_system': 'systemd',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': False,
        'privacy_tools': False,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['lxqt', 'xfce'],
        'init_options': ['systemd', 'sysvinit'],
        'audio_options': ['none', 'cli']
    },
    'java-dev': {
        'description': 'Java development environment with UI',
        'size_gb': 10,
        'build_time_hours': 6,
        'packages': ['base', 'network', 'ssh', 'xorg', 'xfce', 'apps', 'java', 'maven', 'gradle', 'tomcat', 'jenkins', 'docker'],
        'desktop': 'xfce',
        'init_system': 'systemd',
        'audio': 'none',
        'java_dev': True,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['xfce', 'gnome', 'kde'],
        'init_options': ['systemd', 'sysvinit'],
        'audio_options': ['none']
    },
    'secure': {
        'description': 'Security-hardened system with privacy tools',
        'size_gb': 6,
        'build_time_hours': 5,
        'packages': ['base', 'network', 'ssh', 'xorg', 'xfce', 'security', 'privacy'],
        'desktop': 'xfce',
        'init_system': 'sysvinit',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': True,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['xfce', 'lxqt'],
        'init_options': ['sysvinit', 'openrc'],
        'audio_options': ['none']
    },
    'server': {
        'description': 'Production-optimized server configuration',
        'size_gb': 2,
        'build_time_hours': 3,
        'packages': ['base', 'network', 'ssh', 'server-tools'],
        'desktop': 'none',
        'init_system': 'sysvinit',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': False,
        'system_updater': True,
        'desktop_options': ['none'],
        'init_options': ['sysvinit', 'systemd', 'openrc', 's6'],
        'audio_options': ['none']
    },
    'full': {
        'description': 'Complete system with everything included',
        'size_gb': 20,
        'build_time_hours': 12,
        'packages': ['all'],
        'desktop': 'gnome',
        'init_system': 'systemd',
        'audio': 'studio',
        'java_dev': True,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': True,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['gnome', 'kde', 'xfce'],
        'init_options': ['systemd', 'sysvinit', 'openrc'],
        'audio_options': ['none', 'cli', 'studio']
    },
    'arm64': {
        'description': 'ARM64 server for Raspberry Pi and SBCs',
        'size_gb': 2,
        'build_time_hours': 3,
        'packages': ['base', 'network', 'ssh'],
        'desktop': 'none',
        'init_system': 'sysvinit',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': False,
        'system_updater': True,
        'cross_compile': True,
        'architecture': 'aarch64',
        'bootloader': 'uboot',
        'desktop_options': ['none', 'xfce'],
        'init_options': ['sysvinit', 'openrc'],
        'audio_options': ['none']
    },
    'audio-cli': {
        'description': 'CLI-only audio production system - headless',
        'size_gb': 2,
        'build_time_hours': 3,
        'packages': ['base', 'network', 'audio-core', 'audio-midi'],
        'desktop': 'none',
        'init_system': 'sysvinit',
        'audio': 'cli',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': False,
        'system_updater': True,
        'desktop_options': ['none', 'xfce'],
        'init_options': ['sysvinit', 'systemd'],
        'audio_options': ['cli', 'studio']
    },
    'audio-studio': {
        'description': 'Full audio production studio with desktop',
        'size_gb': 8,
        'build_time_hours': 6,
        'packages': ['base', 'network', 'xorg', 'xfce', 'audio-core', 'audio-daw', 'audio-plugins', 'audio-midi'],
        'desktop': 'xfce',
        'init_system': 'systemd',
        'audio': 'studio',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': True,
        'privacy_tools': False,
        'live_system': True,
        'system_updater': True,
        'desktop_options': ['xfce', 'gnome'],
        'init_options': ['systemd'],
        'audio_options': ['studio']
    },
    'custom': {
        'description': 'User-defined custom profile - fully configurable',
        'size_gb': 5,
        'build_time_hours': 5,
        'packages': ['base', 'network', 'ssh'],
        'desktop': 'none',
        'init_system': 'sysvinit',
        'audio': 'none',
        'java_dev': False,
        'package_manager': True,
        'security_hardening': False,
        'privacy_tools': False,
        'live_system': False,
        'system_updater': True,
        'desktop_options': ['none', 'xfce', 'gnome', 'kde', 'lxqt'],
        'init_options': ['sysvinit', 'systemd', 'openrc', 'runit', 's6'],
        'audio_options': ['none', 'cli', 'studio']
    }
}

# Profile templates - combining common configurations
PROFILE_TEMPLATES = {
    'desktop': {
        'description': 'Generic desktop profile',
        'desktop_options': ['xfce', 'gnome', 'kde', 'lxqt'],
        'init_options': ['systemd', 'sysvinit', 'openrc'],
        'audio_options': ['none', 'cli', 'studio']
    },
    'server': {
        'description': 'Generic server profile',
        'desktop_options': ['none'],
        'init_options': ['sysvinit', 'systemd', 'openrc', 's6'],
        'audio_options': ['none']
    },
    'audio': {
        'description': 'Generic audio profile',
        'desktop_options': ['none', 'xfce'],
        'init_options': ['sysvinit', 'systemd'],
        'audio_options': ['cli', 'studio']
    },
    'embedded': {
        'description': 'Generic embedded/ARM profile',
        'desktop_options': ['none', 'xfce'],
        'init_options': ['sysvinit', 'openrc'],
        'audio_options': ['none']
    }
}

